# Site settings
title: Steven Atilho
email: contact@stevenatilho.com
description: >-
  Full-Stack Developer | Enterprise Cybersecurity Engineer | Problem Solver
baseurl: ""
url: "https://www.stevenatilho.com"

# Build settings
markdown: kramdown
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - CLAUDE.md

# Collections (for future scalability)
collections:
  services:
    output: true
    permalink: /services/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
